branch-defaults:
  main:
    environment: null
    group_suffix: null
  master:
    environment: gujarat-police-dev
deploy:
  artifact: target/gujarat_police-0.0.1-SNAPSHOT.jar
environment-defaults:
  gujarat-police-dev:
    branch: master
    repository: gujarat_police
global:
  application_name: gujarat_police
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: Corretto 17 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: V3
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
